### ISSUE TITLE
Vzorová automatizace.

### ISSUE THREAD

**Issue by DavidNetron** [rnovacek/homeassistant_cz_energy_spot_prices#10]

**Comment by DavidNetron** [comment]
Dobrý den.
Integrace je super. Mam jednoduché zadání. Potřebuji sepnout rele integrovane v HA při nejnižší ceně . . Pokouším se o to už nějakou dobu, ale jsem začátečník. Mohl bych poprosit o nějaký jednoduchý vzor takové automatizace ? Tuším že se to nastaví skrze známky 1-24 jako atribut, ale stále mě to nechodí. Děkuji velice za odpověď

**Comment by foxzqw** [comment]
To řeší hodnota `sensor.current_spot_electricity_hour_order` 
`1` je nejlevnější atd.

Tohle by mělo fungovat:
```
alias: sepnout rele integrovane v HA při nejnižší ceně
trigger:
  - platform: state
    entity_id:
      - sensor.current_spot_electricity_hour_order
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.current_spot_electricity_hour_order
        below: 2
    then:
      - type: turn_on
        entity_id: #relé, které chceš zapnout
    else:
      - type: turn_off
        entity_id: #zajistí vypnutí pokud neplatí podmínka výše
    enabled: true
mode: single
```
