### ISSUE TITLE
Lepší UX/UI

### ISSUE THREAD

**Issue by imatrixcz** [rnovacek/homeassistant_cz_energy_spot_prices#76]
Šlo by graf vylepšit tak, aby byl barevný a reflektoval tak minima, středy a výšky? Ve stylu jako to je třeba k vidění na https://spotovaelektrina.cz/denni-ceny/2024-12-03

Díky!

**Comment by Paja-git** [comment]
The integration has no UI/UX. it just makes sensors. The chart from the Read.me is based on the HACS Apex-chart card. You can use the its experimental features. RTFM.

**Comment by 731mat** [comment]
> Šlo by graf vylepšit tak, aby byl barevný a reflektoval tak minima, středy a výšky? Ve stylu jako to je třeba k vidění na https://spotovaelektrina.cz/denni-ceny/2024-12-03
> 
> Díky!

Ahoj, jop, normálně tam dáš treshold. Musíš hledat v dokumentaci od pluginu custom:apexcharts-card

`
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
graph_span: 2d
span:
  start: day
now:
  show: true
  label: Now
series:
  - entity: sensor.current_spot_electricity_price
    float_precision: 2
    type: column # or "line" if you prefer
    show:
      in_header: raw
    color: "#0F0"
    color_threshold:
      - value: 0
        color: "#0F0"
      - value: 2
        color: "#0C0"
      - value: 4
        color: "#090"
      - value: 6
        color: "#060"
      - value: 8
        color: "#030"
    data_generator: |
      return Object.entries(entity.attributes).map(([date, value], index) => {
        return [new Date(date).getTime(), value];
      });

`

**Comment by vwcxi** [comment]
U mne to přes "color_threshold" nefungovalo, ale přes "plotOptions"

```
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
graph_span: 2d
span:
  start: day
now:
  show: true
  label: Teď
series:
  - entity: sensor.current_spot_electricity_price
    float_precision: 2
    type: column
    show:
      in_header: raw
    data_generator: |
      return Object.entries(entity.attributes.prices).map(([idx, row]) => {
        var date = Object.keys(row)[0];
        var price = Object.values(row)[0];

        return [new Date(date).getTime(), price];
      });
apex_config:
  plotOptions:
    bar:
      colors:
        ranges:
          - from: 0
            to: 3
            color: "#00FF00"
          - from: 3.01
            to: 5.5
            color: "#32CD32"
          - from: 5.51
            to: 7
            color: "#228B22"
          - from: 7.01
            to: 9
            color: "#20B2AA"
          - from: 9.01
            to: 12
            color: "#FFD700"
          - from: 12.01
            to: 15
            color: "#FF7F50"
          - from: 15.01
            to: 25
            color: "#FF0000"
          - from: 25.01
            to: 50
            color: "#000000"
```
