### ISSUE TITLE
Apex Chart

### ISSUE THREAD

**Issue by vitjurasek** [rnovacek/homeassistant_cz_energy_spot_prices#78]
Lze prosím nějak ovlivnit plovoucí tooltip s hodnotou? Na počítači to je super, ale ne mobilu po kliknutí do grafu skryje tooltip s cenou všechny sloupce a nedá se to pořádně použít. Případně jak donutit tooltip zobrazovat se fixně na jedné pozici, ideálně nad grafem? 

A ještě - není k dispozici komponenta, která by vypsala ceny v tabulce?

moc díky

**Comment by rnovacek** [comment]
Tohle tomu tooltipu trochu pomůže, ale perfektní to není:

```
apex_config:
  xaxis:
    tooltip:
      enabled: false
  tooltip:
    fixed:
      enabled: true
      position: topRight
      offsetY: -54
```

S komponentou na tabulku neporadím, taky by se mi hodila.
